# -*- coding: utf-8 -*-
"""UASproyek.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4Cf78ovKqDjfB8MEZJ3naulePFnu8EX
"""

from google.colab import drive
drive.mount('https://drive.google.com/file/d/11-t2HrSm3rsoH_8zPmmmJ03uvWz1PnPj/view?usp=drive_link/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/MyDrive/UAS'

#pip install pandas

import pandas as pd

def loadGejala():
	gejala = pd.read_csv('/content/drive/MyDrive/UAS/tb_gejala.csv', delimiter=";")
	gejala.drop('id', inplace=True, axis=1)
	return gejala
	# print(gejala)

def loadPenyakit():
	penyakit = pd.read_csv('/content/drive/MyDrive/UAS/tb_penyakit.csv', delimiter=";", index_col = 'id')
	# penyakit.drop('id', inplace=True, axis=1)
	# print(penyakit)
	return penyakit

def loadRule():
	rule = pd.read_csv('/content/drive/MyDrive/UAS/tb_rule.csv', delimiter=";", index_col = 'id')
	return rule

def getInput(message,response = []):
	if not response:
		return input(message)
	else:
		resok = False
		tempres = None
		while resok is not True:
			tempres = input(message)
			if tempres not in response:
				print("silahkan masukan ","/".join(response))
				resok = False
			else:
				resok = True
		return tempres

if __name__ == "__main__":
	gejala = loadGejala()
	penyakit = loadPenyakit()
	# print(penyakit.loc[5,'penyakit'])
	rules = loadRule()
	checkRule = {}
	for index, row in rules.iterrows():
		# print(index, row.to_dict())
		checkRule[index]=row.to_dict()
	print("")
	print("Halo! Saya adalah CN-31mei2024t, Saya akan mendiagnosa penyakit yang anda alami!")
	print("Oleh karena itu anda harus menjawab beberapa gejala yang anda alami")
	print("Apakah anda merasakan beberapa gejala dibawah ini(y/t):")
	print("")
	input("tekan enter untuk melanjutkan")


	resGejala = {}

	for index, row in gejala.iterrows():
		ans = getInput(str(index+1)+". "+row['gejala'].strip()+" ? ",['y','t'])
		if ans.lower() == 'y':
			resGejala[row['kode']]=1
		else:
			resGejala[row['kode']]=0

	fidx = None
	# print(resGejala)
	for c in checkRule.keys():
		if resGejala == checkRule[c]:
			fidx = c
	if fidx is not None:
		print("")
		# print(penyakit.iloc[[fidx,0]],penyakit.iloc[[fidx,1]],penyakit.iloc[[fidx,2]])
		print("Anda Teridentifikasi Menderita ")
		print(penyakit.loc[fidx,'penyakit'])
		print("")
		print(penyakit.loc[fidx,'info'])
		print("")
		print("Penanganan")
	else:
		print("Maaf penyakit anda tidak terdeteksi")
